// Template catalog for resume styling
// Each template has unique layout, alignment, and structural differences
const templates = {
  classic: {
    label: 'Classic',
    layout: 'traditional', // Left-aligned, simple lines
    pdf: {
      font: 'Times-Roman',
      headingFont: 'Times-Bold',
      titleColor: '#111111',
      headingColor: '#111111',
      bodyColor: '#222222',
      contactColor: '#444444',
      accentColor: '#cccccc',
      titleSize: 20,
      headingSize: 14,
      subheadingSize: 12,
      bodySize: 11,
      lineGap: 2,
      sectionGap: 0.65,
      margin: 55,
      titleAlign: 'left',
      contactAlign: 'left',
      headerStyle: 'simple', // Simple text, light line
    },
    docx: {
      font: 'Times New Roman',
      headingFont: 'Times New Roman',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '111111',
      headingColor: '111111',
      bodyColor: '222222',
      contactColor: '444444',
      accentColor: 'cccccc',
      headingAfter: 120,
      headingBefore: 220,
      bulletSpacing: 90,
      bodyAfter: 125,
      indent: 380,
      titleAfter: 160,
      contactAfter: 230,
    },
  },
  modern: {
    label: 'Modern Accent',
    layout: 'accented',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#0f766e',
      headingColor: '#0b4f4a',
      bodyColor: '#1f1b16',
      contactColor: '#1f1b16',
      accentColor: '#0f766e',
      titleSize: 20,
      headingSize: 14,
      subheadingSize: 12,
      bodySize: 11,
      lineGap: 2.2,
      sectionGap: 0.7,
      margin: 50,
      titleAlign: 'left',
      contactAlign: 'left',
      headerStyle: 'accented', // Bold accent underline
      sectionDivider: 'accent-line', // Colored line under section title
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '0f766e',
      headingColor: '0b4f4a',
      bodyColor: '1f1b16',
      contactColor: '1f1b16',
      accentColor: '0f766e',
      headingAfter: 120,
      headingBefore: 200,
      bulletSpacing: 90,
      bodyAfter: 120,
      indent: 380,
      titleAfter: 140,
      contactAfter: 200,
    },
  },
  minimal: {
    label: 'Minimal',
    layout: 'minimalist',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica',
      titleColor: '#111827',
      headingColor: '#111827',
      bodyColor: '#111827',
      contactColor: '#6b7280',
      accentColor: '#d1d5db',
      titleSize: 20,
      headingSize: 12,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.2,
      sectionGap: 0.6,
      margin: 50,
      titleAlign: 'center',
      contactAlign: 'center',
      headerStyle: 'minimalist'
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '111827',
      headingColor: '111827',
      bodyColor: '111827',
      contactColor: '6b7280',
      accentColor: 'd1d5db',
      headingAfter: 110,
      headingBefore: 160,
      bulletSpacing: 85,
      bodyAfter: 115,
      indent: 360,
      titleAfter: 135,
      contactAfter: 190,
    },
  },
  midnight: {
    label: 'Midnight',
    layout: 'bordered',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#12326f',
      headingColor: '#12326f',
      bodyColor: '#0e172a',
      contactColor: '#1f4b99',
      accentColor: '#1f4b99',
      titleSize: 22,
      headingSize: 13,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.1,
      sectionGap: 0.65,
      margin: 48,
      titleAlign: 'left',
      contactAlign: 'left',
      headerStyle: 'bordered', // Left border accent
      leftBorderColor: '#1f4b99',
      leftBorderWidth: 4,
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '12326f',
      headingColor: '12326f',
      bodyColor: '0e172a',
      contactColor: '1f4b99',
      accentColor: '1f4b99',
      headingAfter: 110,
      headingBefore: 180,
      bulletSpacing: 90,
      bodyAfter: 115,
      indent: 370,
      titleAfter: 150,
      contactAfter: 210,
    },
  },
  sunrise: {
    label: 'Sunrise',
    layout: 'sidebar-right',
    pdf: {
      font: 'Georgia',
      headingFont: 'Georgia-Bold',
      titleColor: '#9a3412',
      headingColor: '#9a3412',
      bodyColor: '#4a2b16',
      contactColor: '#f97316',
      accentColor: '#f97316',
      titleSize: 21,
      headingSize: 13,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.2,
      sectionGap: 0.7,
      margin: 45,
      titleAlign: 'left',
      contactAlign: 'left',
      headerStyle: 'decorative', // Orange accent bar above title
      topBarHeight: 6,
      topBarColor: '#f97316',
    },
    docx: {
      font: 'Georgia',
      headingFont: 'Georgia Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '9a3412',
      headingColor: '9a3412',
      bodyColor: '4a2b16',
      contactColor: 'f97316',
      accentColor: 'f97316',
      headingAfter: 130,
      headingBefore: 210,
      bulletSpacing: 100,
      bodyAfter: 125,
      indent: 400,
      titleAfter: 160,
      contactAfter: 230,
    },
  },
  mint: {
    label: 'Mint',
    layout: 'centered',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#115e59',
      headingColor: '#115e59',
      bodyColor: '#064e3b',
      contactColor: '#2dd4bf',
      accentColor: '#2dd4bf',
      titleSize: 20,
      headingSize: 12,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.3,
      sectionGap: 0.65,
      margin: 50,
      titleAlign: 'center',
      contactAlign: 'center',
      headerStyle: 'centered', // Centered with subtle underline
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '115e59',
      headingColor: '115e59',
      bodyColor: '064e3b',
      contactColor: '2dd4bf',
      accentColor: '2dd4bf',
      headingAfter: 125,
      headingBefore: 200,
      bulletSpacing: 95,
      bodyAfter: 120,
      indent: 390,
      titleAfter: 155,
      contactAfter: 220,
    },
  },
  sidebar: {
    label: 'Sidebar',
    layout: 'bordered',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#1e293b',
      headingColor: '#1e293b',
      bodyColor: '#111827',
      contactColor: '#475569',
      accentColor: '#1e40af',
      titleSize: 21,
      headingSize: 12.5,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.1,
      sectionGap: 0.65,
      margin: 50,
      titleAlign: 'left',
      contactAlign: 'left',
      leftBorderColor: '#1e40af',
      leftBorderWidth: 4,
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '1e293b',
      headingColor: '1e293b',
      bodyColor: '111827',
      contactColor: '475569',
      accentColor: '1e40af',
      headingAfter: 115,
      headingBefore: 185,
      bulletSpacing: 90,
      bodyAfter: 120,
      indent: 380,
      titleAfter: 150,
      contactAfter: 210,
    },
  },
  executive: {
    label: 'Executive',
    layout: 'formal',
    pdf: {
      font: 'Courier',
      headingFont: 'Courier-Bold',
      titleColor: '#000000',
      headingColor: '#d97706',
      bodyColor: '#1a1a1a',
      contactColor: '#374151',
      accentColor: '#d97706',
      titleSize: 24,
      headingSize: 13,
      subheadingSize: 11,
      bodySize: 10,
      lineGap: 2.2,
      sectionGap: 0.75,
      margin: 50,
      titleAlign: 'center',
      contactAlign: 'center',
      headerStyle: 'formal', // Centered with thick line dividers
      dividerStyle: 'thick-line',
      dividerColor: '#d97706',
    },
    docx: {
      font: 'Courier New',
      headingFont: 'Courier New Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '000000',
      headingColor: 'd97706',
      bodyColor: '1a1a1a',
      contactColor: '374151',
      accentColor: 'd97706',
      headingAfter: 140,
      headingBefore: 220,
      bulletSpacing: 100,
      bodyAfter: 135,
      indent: 400,
      titleAfter: 170,
      contactAfter: 240,
    },
  },
  clean: {
    label: 'Clean Modern',
    layout: 'minimalist',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#7c3aed',
      headingColor: '#7c3aed',
      bodyColor: '#374151',
      contactColor: '#6b7280',
      accentColor: '#7c3aed',
      titleSize: 19,
      headingSize: 12,
      subheadingSize: 10.5,
      bodySize: 10,
      lineGap: 2.4,
      sectionGap: 0.7,
      margin: 50,
      titleAlign: 'left',
      contactAlign: 'left',
      headerStyle: 'minimalist', // Very sparse, dot separator for contact
      contactSeparator: ' • ',
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '7c3aed',
      headingColor: '7c3aed',
      bodyColor: '374151',
      contactColor: '6b7280',
      accentColor: '7c3aed',
      headingAfter: 140,
      headingBefore: 220,
      bulletSpacing: 105,
      bodyAfter: 135,
      indent: 410,
      titleAfter: 180,
      contactAfter: 250,
    },
  },
  bold: {
    label: 'Bold Impact',
    layout: 'formal',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#1f2937',
      headingColor: '#374151',
      bodyColor: '#1f2937',
      contactColor: '#6b7280',
      accentColor: '#374151',
      titleSize: 22,
      headingSize: 13,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.2,
      sectionGap: 0.7,
      margin: 48,
      titleAlign: 'center',
      contactAlign: 'center',
      dividerColor: '#374151',
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '1f2937',
      headingColor: '374151',
      bodyColor: '1f2937',
      contactColor: '6b7280',
      accentColor: '374151',
      headingAfter: 145,
      headingBefore: 230,
      bulletSpacing: 100,
      bodyAfter: 135,
      indent: 410,
      titleAfter: 175,
      contactAfter: 245,
    },
  },
  creative: {
    label: 'Creative',
    layout: 'elegant',
    pdf: {
      font: 'Georgia',
      headingFont: 'Georgia-Bold',
      titleColor: '#059669',
      headingColor: '#059669',
      bodyColor: '#1f2937',
      contactColor: '#10b981',
      accentColor: '#34d399',
      titleSize: 22,
      headingSize: 12,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.4,
      sectionGap: 0.6,
      margin: 52,
      titleAlign: 'left',
      contactAlign: 'left',
      headerStyle: 'elegant', // Elegant with small decorative elements
      useDecorative: true,
    },
    docx: {
      font: 'Georgia',
      headingFont: 'Georgia Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '059669',
      headingColor: '059669',
      bodyColor: '1f2937',
      contactColor: '10b981',
      accentColor: '34d399',
      headingAfter: 145,
      headingBefore: 235,
      bulletSpacing: 105,
      bodyAfter: 140,
      indent: 415,
      titleAfter: 175,
      contactAfter: 250,
    },
  },
  centered_serif: {
    label: 'Centered Serif',
    layout: 'formal',
    pdf: {
      font: 'Georgia',
      headingFont: 'Georgia-Bold',
      titleColor: '#1f2937',
      headingColor: '#374151',
      bodyColor: '#1f2937',
      contactColor: '#6b7280',
      accentColor: '#374151',
      titleSize: 22,
      headingSize: 12.5,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.2,
      sectionGap: 0.7,
      margin: 50,
      titleAlign: 'center',
      contactAlign: 'center',
      dividerColor: '#374151',
    },
    docx: {
      font: 'Georgia',
      headingFont: 'Georgia Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '1f2937',
      headingColor: '374151',
      bodyColor: '1f2937',
      contactColor: '6b7280',
      accentColor: '374151',
      headingAfter: 145,
      headingBefore: 225,
      bulletSpacing: 100,
      bodyAfter: 135,
      indent: 400,
      titleAfter: 175,
      contactAfter: 245,
    },
  },
  compact_pro: {
    label: 'Compact Professional',
    layout: 'accented',
    pdf: {
      font: 'Helvetica',
      headingFont: 'Helvetica-Bold',
      titleColor: '#111827',
      headingColor: '#1f2937',
      bodyColor: '#111827',
      contactColor: '#6b7280',
      accentColor: '#4b5563',
      titleSize: 19,
      headingSize: 12,
      subheadingSize: 10.5,
      bodySize: 10,
      lineGap: 1.85,
      sectionGap: 0.5,
      margin: 42,
      titleAlign: 'left',
      contactAlign: 'left',
    },
    docx: {
      font: 'Helvetica',
      headingFont: 'Helvetica Bold',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '111827',
      headingColor: '1f2937',
      bodyColor: '111827',
      contactColor: '6b7280',
      accentColor: '4b5563',
      headingAfter: 120,
      headingBefore: 190,
      bulletSpacing: 85,
      bodyAfter: 120,
      indent: 360,
      titleAfter: 150,
      contactAfter: 210,
    },
  },
  left_bar: {
    label: 'Left Bar',
    layout: 'bordered',
    pdf: {
      font: 'Times-Roman',
      headingFont: 'Times-Bold',
      titleColor: '#1f2937',
      headingColor: '#1f2937',
      bodyColor: '#111827',
      contactColor: '#6b7280',
      accentColor: '#374151',
      titleSize: 21,
      headingSize: 12.5,
      subheadingSize: 11,
      bodySize: 10.5,
      lineGap: 2.0,
      sectionGap: 0.65,
      margin: 50,
      titleAlign: 'left',
      contactAlign: 'left',
      leftBorderColor: '#374151',
      leftBorderWidth: 3,
    },
    docx: {
      font: 'Times New Roman',
      headingFont: 'Times New Roman',
      // Colors mirrored from PDF (hex without '#')
      titleColor: '1f2937',
      headingColor: '1f2937',
      bodyColor: '111827',
      contactColor: '6b7280',
      accentColor: '374151',
      headingAfter: 125,
      headingBefore: 200,
      bulletSpacing: 90,
      bodyAfter: 125,
      indent: 380,
      titleAfter: 160,
      contactAfter: 225,
    },
  },
};

function getTemplate(key) {
  return templates[key] || templates.classic;
}

const templateKeys = Object.keys(templates);

module.exports = {
  templates,
  templateKeys,
  getTemplate,
};
